// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlayerManagement.Data;

#nullable disable

namespace PlayerManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlayerManagement.Models.BloodGroup", b =>
                {
                    b.Property<int>("BloodGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BloodGroupId"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("BloodGroupId")
                        .HasName("PK__BloodGro__4398C68FDE0DDF3E");

                    b.ToTable("BloodGroup", (string)null);

                    b.HasData(
                        new
                        {
                            BloodGroupId = 1,
                            GroupName = "A+"
                        },
                        new
                        {
                            BloodGroupId = 2,
                            GroupName = "A-"
                        },
                        new
                        {
                            BloodGroupId = 3,
                            GroupName = "B+"
                        },
                        new
                        {
                            BloodGroupId = 4,
                            GroupName = "B-"
                        });
                });

            modelBuilder.Entity("PlayerManagement.Models.Gender", b =>
                {
                    b.Property<int>("GenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenderId"));

                    b.Property<string>("GenderName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("GenderId")
                        .HasName("PK__Gender__4E24E9F788C32ACD");

                    b.ToTable("Gender", (string)null);

                    b.HasData(
                        new
                        {
                            GenderId = 1,
                            GenderName = "Male"
                        },
                        new
                        {
                            GenderId = 2,
                            GenderName = "Female"
                        },
                        new
                        {
                            GenderId = 3,
                            GenderName = "Other"
                        });
                });

            modelBuilder.Entity("PlayerManagement.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<int>("BloodGroupId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FathersName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastEducationalQualification")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("MothersName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NidNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PlayerWeight")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int>("ReligionId")
                        .HasColumnType("int");

                    b.Property<int>("SportsTypeId")
                        .HasColumnType("int");

                    b.HasKey("PlayerId")
                        .HasName("PK__Player__4A4E74C8446FF317");

                    b.HasIndex("BloodGroupId");

                    b.HasIndex("GenderId");

                    b.HasIndex("ReligionId");

                    b.HasIndex("SportsTypeId");

                    b.ToTable("Player", (string)null);
                });

            modelBuilder.Entity("PlayerManagement.Models.PlayerTrainingAssignment", b =>
                {
                    b.Property<int>("PlayerTrainingAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerTrainingAssignmentId"));

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TrainingDate")
                        .HasColumnType("datetime");

                    b.Property<int>("TrainingId")
                        .HasColumnType("int");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("PlayerTrainingAssignmentId")
                        .HasName("PK__PlayerTr__055FA1881DFFF5DE");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TrainingId");

                    b.ToTable("PlayerTrainingAssignment", (string)null);
                });

            modelBuilder.Entity("PlayerManagement.Models.Religion", b =>
                {
                    b.Property<int>("ReligionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReligionId"));

                    b.Property<string>("ReligionName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ReligionId")
                        .HasName("PK__Religion__D3ADAB6A825E3C0E");

                    b.ToTable("Religion", (string)null);

                    b.HasData(
                        new
                        {
                            ReligionId = 1,
                            ReligionName = "Islam"
                        },
                        new
                        {
                            ReligionId = 2,
                            ReligionName = "Hinduism"
                        },
                        new
                        {
                            ReligionId = 3,
                            ReligionName = "Christianism"
                        },
                        new
                        {
                            ReligionId = 4,
                            ReligionName = "Buddism"
                        });
                });

            modelBuilder.Entity("PlayerManagement.Models.SportsType", b =>
                {
                    b.Property<int>("SportsTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SportsTypeId"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("SportsTypeId")
                        .HasName("PK__SportsTy__8F679832FD582307");

                    b.ToTable("SportsType", (string)null);

                    b.HasData(
                        new
                        {
                            SportsTypeId = 1,
                            TypeName = "Cricket"
                        },
                        new
                        {
                            SportsTypeId = 2,
                            TypeName = "Football"
                        },
                        new
                        {
                            SportsTypeId = 3,
                            TypeName = "Badminton"
                        },
                        new
                        {
                            SportsTypeId = 4,
                            TypeName = "Swimming"
                        });
                });

            modelBuilder.Entity("PlayerManagement.Models.Training", b =>
                {
                    b.Property<int>("TrainingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainingId"));

                    b.Property<string>("TrainingName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("TrainingId")
                        .HasName("PK__Training__E8D71D828C6BE2AD");

                    b.ToTable("Training");

                    b.HasData(
                        new
                        {
                            TrainingId = 1,
                            TrainingName = "Batting"
                        },
                        new
                        {
                            TrainingId = 2,
                            TrainingName = "Bowling"
                        },
                        new
                        {
                            TrainingId = 3,
                            TrainingName = "Fielding"
                        },
                        new
                        {
                            TrainingId = 4,
                            TrainingName = "Tactical"
                        },
                        new
                        {
                            TrainingId = 5,
                            TrainingName = "Strength"
                        });
                });

            modelBuilder.Entity("PlayerManagement.Models.Player", b =>
                {
                    b.HasOne("PlayerManagement.Models.BloodGroup", "BloodGroup")
                        .WithMany("Players")
                        .HasForeignKey("BloodGroupId")
                        .IsRequired()
                        .HasConstraintName("FK__Player__BloodGro__300424B4");

                    b.HasOne("PlayerManagement.Models.Gender", "Gender")
                        .WithMany("Players")
                        .HasForeignKey("GenderId")
                        .IsRequired()
                        .HasConstraintName("FK__Player__GenderId__2E1BDC42");

                    b.HasOne("PlayerManagement.Models.Religion", "Religion")
                        .WithMany("Players")
                        .HasForeignKey("ReligionId")
                        .IsRequired()
                        .HasConstraintName("FK__Player__Religion__30F848ED");

                    b.HasOne("PlayerManagement.Models.SportsType", "SportsType")
                        .WithMany("Players")
                        .HasForeignKey("SportsTypeId")
                        .IsRequired()
                        .HasConstraintName("FK__Player__SportsTy__2F10007B");

                    b.Navigation("BloodGroup");

                    b.Navigation("Gender");

                    b.Navigation("Religion");

                    b.Navigation("SportsType");
                });

            modelBuilder.Entity("PlayerManagement.Models.PlayerTrainingAssignment", b =>
                {
                    b.HasOne("PlayerManagement.Models.Player", "Player")
                        .WithMany("PlayerTrainingAssignments")
                        .HasForeignKey("PlayerId")
                        .IsRequired()
                        .HasConstraintName("FK__PlayerTra__Playe__34C8D9D1");

                    b.HasOne("PlayerManagement.Models.Training", "Training")
                        .WithMany("PlayerTrainingAssignments")
                        .HasForeignKey("TrainingId")
                        .IsRequired()
                        .HasConstraintName("FK__PlayerTra__Train__35BCFE0A");

                    b.Navigation("Player");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("PlayerManagement.Models.BloodGroup", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("PlayerManagement.Models.Gender", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("PlayerManagement.Models.Player", b =>
                {
                    b.Navigation("PlayerTrainingAssignments");
                });

            modelBuilder.Entity("PlayerManagement.Models.Religion", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("PlayerManagement.Models.SportsType", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("PlayerManagement.Models.Training", b =>
                {
                    b.Navigation("PlayerTrainingAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
